apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-backend-config
  namespace: hr-system
  labels:
    app: hr-backend
    app.kubernetes.io/name: hr-backend
    app.kubernetes.io/part-of: hr-system
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: mysql.hr-system.svc.cluster.local
  DB_NAME: hrdb
  DB_USER: hr
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
---
apiVersion: v1
kind: Secret
metadata:
  name: hr-backend-secret
  namespace: hr-system
  labels:
    app: hr-backend
    app.kubernetes.io/name: hr-backend
    app.kubernetes.io/part-of: hr-system
type: Opaque
stringData:
  DB_PASSWORD: hrpass
---

---
apiVersion: v1
kind: Service
metadata:
  name: hr-backend
  namespace: hr-system
  labels:
    app: hr-backend
    App: hr-backend
    app.kubernetes.io/name: hr-backend
    app.kubernetes.io/part-of: hr-system
spec:
  selector: { app: hr-backend }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
