apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-frontend
  namespace: hr-system
spec:
  replicas: 1
  selector:
    matchLabels: { app: hr-frontend }
  template:
    metadata:
      labels: { app: hr-frontend }
    spec:
      containers:
        - name: hr-frontend
          image: hr-frontend:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: { cpu: "50m", memory: "128Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: hr-frontend
  namespace: hr-system
spec:
  selector: { app: hr-frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
