services:
  mysql:
    image: mysql:8.0
    container_name: hr-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrdb
      MYSQL_USER: hr
      MYSQL_PASSWORD: hrpw
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - ./infra/db/init:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql

  hr-backend:
    container_name: hr-backend
    build:
      context: ./hr-backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://mysql:3306/hrdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: hr
      DB_PASS: hrpw
    # expose backend to host on 8082 (container listens on 8080)
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep '\"status\":\"UP\"' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  hr-frontend:
    container_name: hr-frontend
    build:
      context: ./hr-frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      hr-backend:
        condition: service_healthy
    # expose frontend to host on 8083
    ports:
      - "8083:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ | grep -i '<title' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
