# k8s/mysql/deployment.yaml
spec:
  template:
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATABASE
              value: hrdb
            - name: MYSQL_USER
              value: hr
            - name: MYSQL_PASSWORD
              value: hrpass
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-pvc
