deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

loki:
  auth_enabled: false

  # Disable structured metadata while on boltdb-shipper
  limits_config:
    allow_structured_metadata: false

  # Runtime storage for local dev (PVC from singleBinary.persistence)
  storage_config:
    filesystem:
      directory: /var/loki

  # Schema (still boltdb-shipper)
  schemaConfig:
    configs:
      - from: "2025-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  # IMPORTANT: provide bucketNames so the helper doesn't nil-deref
  storage:
    use_thanos_objstore: false
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
      bloom: bloom
      compactor: compactor

  # Optional UI toggle
  ui:
    enabled: true
