apiVersion: v1
kind: Secret
metadata:
  name: hr-backend-secret
  namespace: hr-system
  labels:
    app: hr-backend
    app.kubernetes.io/name: hr-backend
    app.kubernetes.io/part-of: hr-system
type: Opaque
stringData:
  DB_PASSWORD: "hrpass"
