apiVersion: v1
kind: Service
metadata:
  name: hr-backend
  namespace: hr-system
  labels:
    app: hr-backend
    app.kubernetes.io/name: hr-backend
    app.kubernetes.io/part-of: hr-system
spec:
  selector:
    app: hr-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
