# k8s/hr-backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-backend
  namespace: hr-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-backend
  template:
    metadata:
      labels:
        app: hr-backend
    spec:
      containers:
        - name: hr-backend
          image: tomfly2010/hr-backend:0.1.2
          imagePullPolicy: IfNotPresent   # important for local images
          envFrom:
            - configMapRef:
                name: hr-backend-config
            - secretRef:
                name: hr-backend-secret
          ports:
            - containerPort: 8080
