global:
  scrape_interval: 5s       # how often to scrape metrics
  evaluation_interval: 5s   # how often to evaluate rules
  scrape_timeout: 4s        # timeout per scrape

  # Optional: external labels for identification (helpful if you ever federate)
  external_labels:
    monitor: 'hr-monitor'

# ------------------------------
# Scrape configurations
# ------------------------------
scrape_configs:
  # --- hr-backend: Spring Boot actuator metrics ---
  - job_name: 'hr-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['hr-backend:8080']
        labels:
          application: 'hr-backend'
          env: 'docker'
          team: 'hr'

  # --- Prometheus self-monitoring ---
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'prometheus'

  # --- Loki metrics (log aggregation backend) ---
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          application: 'loki'

  # --- Docker container metrics (optional but useful) ---
  # This lets Prometheus monitor the Docker Engine itself if needed.
  - job_name: 'docker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9323']
        labels:
          application: 'docker-engine'
