apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - pools/ip-pool-main.yaml
  - pools/ip-pool-monitoring.yaml
  - l2adverts/l2adv-main.yaml
  - l2adverts/l2adv-monitoring.yaml
